name: task_orangebayhurghada
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter

  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.8
  # A Flutter package to use fonts from fonts.google.com. Supports HTTP fetching, caching, and asset bundling.
  google_fonts: ^6.3.2
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.7
  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1
  # A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.9.0
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0
  # A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
  bloc: ^9.0.1
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^8.2.0
  # Flutter widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^9.1.1
  # Converts already built widgets into skeleton loaders with no extra effort.
  skeletonizer: ^2.1.0+1
  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.3.2
  # A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
  flutter_rating_bar: ^4.0.1
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.2.3
  # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share_plus: ^12.0.1
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.1
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
